# Problem 2
# Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

# My favorite: N/A yet!

# ////////////////////////////////////////////////////////////////////////////////////////////////////////////
# Approach 1

MAX_FIB <- 4000000
fib <- c(1, 1)
sum_even <- 0
while ( fib[1] < MAX_FIB ) {
    fib <- c( fib[2], fib[1] + fib[2] )
    if ( fib[1] %% 2 == 0 ) {
        sum_even <- sum_even + fib[1]
    }
}
cat(sum_even, fill=TRUE)

# Remove all objects except for functions
rm(list = setdiff(ls(), lsf.str()))

# ////////////////////////////////////////////////////////////////////////////////////////////////////////////
# Approach 2

fib <- numeric(0)
fib[1] <- 1
fib[2] <- 2
index <- 3
tmp <- fib[1] + fib[2]
while (tmp < 4000000) {
    fib[index] <- tmp 
    tmp <- fib[index] + fib[index-1]
    index <- index + 1
}
sum(fib[fib%%2 == 0])

# Remove all objects except for functions
rm(list = setdiff(ls(), lsf.str()))

# ////////////////////////////////////////////////////////////////////////////////////////////////////////////
# Approach 3

fib <- c(1, 2)
while (max(fib) < 4E+06) { 
    len <- length(fib)
    fib <- c(fib, fib[len - 1] + fib[len])
}
answer <- sum(fib[fib %% 2 == 0])
print(answer)

# Remove all objects except for functions
rm(list = setdiff(ls(), lsf.str()))

# ////////////////////////////////////////////////////////////////////////////////////////////////////////////
# Approach 4

?gmp
library(gmp)
i <- 1
answer <- 0
fib <- fibnum(1)
while (fibnum(i) <= 4E6) {
    fib <- fibnum(i)
    if (fib %% 2 == 0) answer <- answer + fib
    i <- i + 1
}
print(answer)

# Remove all objects except for functions
rm(list = setdiff(ls(), lsf.str()))


